name: Deployment Pipeline

on:
#  pull_request:
  push:

jobs:
  Pre-Commit:
    uses: ./.github/workflows/pre-commit.yml

  Check-rst-Documentation:
    needs: Pre-Commit
    uses: ./.github/workflows/check-rst-documentation.yml

  CI:
    needs: Check-rst-Documentation
    uses: ./.github/workflows/ci.yml

  Build-and-Deploy-to-Production:
    needs: CI
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build-and-deploy-to-production.yml
